# Generated by Django 4.0.3 on 2022-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phn_number',
            field=models.IntegerField(default=9999999999),
        ),
    ]
