# Generated by Django 4.0.3 on 2022-05-10 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
