# Generated by Django 4.0.3 on 2022-05-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('date', models.DateTimeField()),
                ('timestamp_in', models.TimeField()),
                ('timestamp_out', models.TimeField()),
                ('rm_approval', models.BooleanField(default=False)),
                ('leave_application', models.BooleanField(default=False)),
                ('leave_application_approval', models.BooleanField(default=False)),
                ('timing_duration', models.TimeField()),
            ],
        ),
    ]
