# Generated by Django 3.2.13 on 2022-05-12 08:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=users.models.upload_location),
        ),
    ]
