# Generated by Django 3.2.13 on 2022-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
