# Generated by Django 3.2.13 on 2022-05-13 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 9, 32, 11, 527726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp_out',
            field=models.TimeField(blank=True),
        ),
    ]
