# Generated by Django 3.2.13 on 2022-05-13 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20220513_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 9, 49, 37, 647164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timing_duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
