# Generated by Django 3.2.13 on 2022-05-16 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20220513_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='rm',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 5, 6, 39, 721251, tzinfo=utc)),
        ),
    ]
