# Generated by Django 3.2.13 on 2022-05-16 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20220516_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 6, 26, 49, 550653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
