# Generated by Django 3.2.13 on 2022-05-16 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20220516_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 6, 49, 27, 558767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timing_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
