# Generated by Django 3.2.13 on 2022-05-16 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20220516_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 6, 50, 23, 788490, tzinfo=utc)),
        ),
    ]
