# Generated by Django 3.2.13 on 2022-05-16 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20220516_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 7, 7, 43, 666365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timing_duration',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
