# Generated by Django 3.2.13 on 2022-05-16 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp_in',
            field=models.DateTimeField(default=datetime.time(0, 0)),
        ),
    ]
