# Generated by Django 3.2.13 on 2022-05-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20220517_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timing_duration',
        ),
    ]
