# Generated by Django 3.2.13 on 2022-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_attendance_timing_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='timing_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
