# Generated by Django 3.2.13 on 2022-05-18 06:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0017_attendance_timing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 18)),
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('loss of pay', 'LOSS OF PAY'), ('comp - off', 'COMP - OFF')], default='loss of pay', max_length=20)),
                ('from_date', models.DateTimeField(default=datetime.date(2022, 5, 18))),
                ('to_date', models.DateTimeField()),
                ('from_session', models.CharField(choices=[('session1', 'SESSION1'), ('session2', 'SESSION2')], default='session1', max_length=20)),
                ('to_session', models.CharField(choices=[('session1', 'SESSION1'), ('session2', 'SESSION2')], default='session2', max_length=20)),
                ('cc_to', models.EmailField(max_length=254)),
                ('contact_details', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('total_leaves', models.IntegerField(blank=True, default=10, null=True)),
                ('leaves_taken', models.IntegerField(blank=True, null=True)),
                ('applying_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
