# Generated by Django 3.2.13 on 2022-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20220518_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplcation',
            name='rm_approval',
            field=models.BooleanField(default=False),
        ),
    ]
