# Generated by Django 3.2.13 on 2022-05-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20220518_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='reason',
            field=models.TextField(),
        ),
    ]
