# Generated by Django 3.2.13 on 2022-05-19 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_leaveapplcation_rm_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='signin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 19)),
        ),
        migrations.AlterField(
            model_name='leaveapplcation',
            name='from_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 19)),
        ),
    ]
