# Generated by Django 3.2.13 on 2022-05-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_leaves_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='email',
            field=models.EmailField(default='aakash1avp@yahoo.com', max_length=254),
        ),
    ]
